### ISSUE TITLE
Suspicious address order along 253rd Street

### ISSUE THREAD

**Issue by ToeBee** [osmlab/nycbuildings#118]
Will probably take boots on the ground to verify but the addresses along 253rd street between Memphis and Weller look suspicious. The addresses go (142-)31, 27, 25, 29 (along with a 23 right on top of the 29 that isn't rendered), 33, 37, 43. I haven't seen any other out of order addresses in the area. Link:  
http://www.openstreetmap.org/#map=19/40.65949/-73.73430

Screenshot: 
![image](https://f.cloud.github.com/assets/348948/2191067/db04c4b6-983b-11e3-8994-1e0d180cd512.png)

**Comment by lxbarth** [comment]
Added a note: http://www.openstreetmap.org/note/492872

Closing here.
