### ISSUE TITLE
TIGER / NYC data disagreeing on street name

### ISSUE THREAD

**Issue by Rub21** [osmlab/nycbuildings#121]
i readed the https://github.com/osmlab/nycbuildings/wiki/Common-issues, but i can't find solution for this. when i have validated,
http://www.openstreetmap.org/way/5711983/history
##### Red rows
the buildins has tag `addr:street: Fort Hill Circle` but Tiger road called   `name: Fort Hill Place`,  could i rename the building ? or how could i work in this case?
##### Green row:
it's possible to add tag `addr:street: Fort Hill Circle` on the build if it not has this tag
![bu](https://f.cloud.github.com/assets/1152236/2275958/b945da92-9f2d-11e3-9ffe-0d9f65af77ff.png)

**Comment by Rub21** [comment]
@lxbarth : I checked those  issues  but there are  not  much differences between New and misaligned TIGER roads and TIGER 2012. 
However  I fixed  a error: 
- [Fixed way](https://www.openstreetmap.org/way/335818003/history) on comment https://github.com/osmlab/nycbuildings/issues/121#issuecomment-36366039 

And the other was fixed by other users:
-  [Fixed way](https://www.openstreetmap.org/way/5714436/history#map=19/40.62539/-74.14705) on comment https://github.com/osmlab/nycbuildings/issues/121#issuecomment-36398842


-  [Fixed way](https://www.openstreetmap.org/way/5712994/history) on comment https://github.com/osmlab/nycbuildings/issues/121#issuecomment-36378343

Would be good that someone who know those places  can fix  the other errors.

**Comment by lxbarth** [comment]
> Would be good that someone who know those places can fix the other errors.

Can you open notes for them?

**Comment by Rub21** [comment]
> Can you open notes for them?

I've opened notes for each error. 
http://www.openstreetmap.org/note/340719
http://www.openstreetmap.org/note/340721
http://www.openstreetmap.org/note/340723
http://www.openstreetmap.org/note/340727
http://www.openstreetmap.org/note/340729

**Comment by lxbarth** [comment]
@Rub21 - next actions here?

**Comment by Rub21** [comment]
@lxbarth , there are not other action here,  Close here.
