### ISSUE TITLE
New review?

### ISSUE THREAD

**Issue by emacsen** [osmlab/nycbuildings#133]
I see lots of ticket reviews are being done, and that's great. Unfortunately they're being done on the same day I had surgery at 8am.  Between being in pain and being on pain killers, I'm barely able to be on the computer for any length of time.

OSM NYC has a meeting scheduled Wednesday. I doubt that I'll feel up to attending, but I can bring the issue up and maybe we can get the NYC community to review outstanding issues.

**Comment by lxbarth** [comment]
Closing here for now as there are no next actions. @emacsen - you're always welcome to open issues here on the queue as you detect them.
