### ISSUE TITLE
Bad streetname merges

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/nycbuildings#134]
I've come across some bad merges with buildings and POIs that happened before and after ordinal fixes. This results in an `addr:street` that has both. These should be manually cleaned up.

![screen shot 2014-07-31 at 6 16 04 pm](https://cloud.githubusercontent.com/assets/58878/3772526/4e6e5f80-1900-11e4-8740-6d8bb1f9f996.png)

I'll script up a way of detecting them and then we can fix them manually.

**Comment by Rub21** [comment]
@aaronlidman , I found those object where using  `addr:street =*;*` https://dl.dropboxusercontent.com/u/43116811/nyc-error-address.osm

# Next Action

Make a script to fix the `addr:street `

**Comment by pnorman** [comment]
Probably 

> Make a script to fix the `addr:street`

probably easier to fix them by hand than doing a mechanical edit

**Comment by aaronlidman** [comment]
> probably easier to fix them by hand than doing a mechanical edit

I agree. @Rub21 Can someone work on fixing these 145 items manually?

**Comment by Rub21** [comment]
@aaronlidman @pnorman  : 
> Can someone work on fixing these 145 items manually?

ok, I will work with Richman on this tas.

**Comment by RichRico** [comment]
ok, Ayudaré en esto

**Comment by Rub21** [comment]
@aaronlidman @pnorman  : I revised @RichRico 's [edition](https://dl.dropboxusercontent.com/u/43116811/osmose-files/RichRico.osm) that is fine.
if are you agree? , close this task

**Comment by Rub21** [comment]
No other action here.  Close
