### ISSUE TITLE
Validator sweep

### ISSUE THREAD

**Issue by aaronlidman** [osmlab/nycbuildings#135]
@Rub21 Can you go over all of the import area and fix any errors from the JOSM validator? You will probably have to download many many small areas and check them one by one.

I have found some areas with duplicate nodes, overlapping buildings, disconnected nodes, or other very simple problems. Some are from the import and some are not but these should all be very simple to fix.

![screen shot 2014-07-31 at 6 48 57 pm](https://cloud.githubusercontent.com/assets/58878/3772864/e7f766a2-1904-11e4-8a24-32779f5e3b89.png)

**Comment by lxbarth** [comment]
@aaronlidman - can you still do this? Or should we just go about fixes manually?

**Comment by lxbarth** [comment]
Not actionable right now.
