### ISSUE TITLE
remove `addr:postcode` ?

### ISSUE THREAD

**Issue by Rub21** [osmlab/nycbuildings#142]
From : https://github.com/osmlab/nycbuildings/issues/139

@lxbarth, Is necessary  remove `addr:postcode` at clean up the special_co address ? we need to know to add in [documentation](https://github.com/osmlab/nycbuildings/wiki/Import-cleanup)

**Comment by lxbarth** [comment]
@Rub21 - the initial import includes the postcode, so yes.

**Comment by lxbarth** [comment]
I updated the wiki accordingly: https://github.com/osmlab/nycbuildings/wiki/Clean-up-special-A-B-addresses
