### ISSUE TITLE
Understanding special_co addresses

### ISSUE THREAD

**Issue by planemad** [osmlab/nycbuildings#143]
While trying to rework on the [workflow for address cleanup](https://github.com/osmlab/nycbuildings/wiki/Import-cleanup), @Rub21 and I discovered inconsistencies in the special_co addresses that require cleanup.

### A address
[446 Grandview Ave](https://www.openstreetmap.org/way/250449001/history) was marked for removal. Another address 2049 Himrod St was located for the same building.
![screenshot 2015-05-25 16 53 13](https://cloud.githubusercontent.com/assets/126868/7796617/b27e85ac-02fe-11e5-8229-eccc9dbc2885.png) 

**http://maps.nyc.gov/**
- Both [446 Grandview Ave](http://maps.nyc.gov/doitt/nycitymap/?searchType=AddressSearch&addressNumber=446%20&street=Grandview%20ave&borough=QUEENS) and [2049 Himrod St](http://maps.nyc.gov/doitt/nycitymap/?searchType=AddressSearch&addressNumber=2049&street=himrod%20st&borough=QUEENS) point to the exact same building

**Google Streetview**
- In streetview we found that [20-49](https://www.google.it/maps/@40.710544,-73.909301,3a,15y,320.98h,92.36t/data=!3m4!1e1!3m2!1sZdfRSLHJcb9ze6rwkvv9GQ!2e0) is the address of the store whose entrance is on Himrod St.
- The entrance to the building itself is on the side and is [446](https://www.google.it/maps/@40.710713,-73.909378,3a,15y,228.91h,88.27t/data=!3m4!1e1!3m2!1s_yE8IkCHA-K20vwhVhFVSA!2e0) on Grandview Ave

### B address
This is a cluster of duplicate addresses but only 3 are marked as B code addresses (red) in [Queens](https://www.openstreetmap.org/node/2568938223).
![screenshot 2015-05-25 19 18 02](https://cloud.githubusercontent.com/assets/126868/7798093/f8743f20-0312-11e5-85bb-5bd908bc4d99.png)

- The street address `Prospect Ave` does not match the actual street name `60th Place`
- This address is valid on [maps.nyc.in](http://maps.nyc.gov/doitt/nycitymap/?searchType=AddressSearch&addressNumber=66-50&street=prospect%20ave&borough=QUEENS)
- The other duplicates follow the same pattern but do not appear to be part of the code B address set

### Conclusion
It is unclear on what the exact status of these special_co A and B addresses are. They all seem to be valid addresses on http://maps.nyc.gov, and in some cases even exist physically as in the first case, so it will be incorrect to remove them.

@lxbarth is there any further documentation or discussion of these addresses and are we 100% sure they need to be cleaned up?

**Comment by lxbarth** [comment]
@planemad - take a look at back story here https://github.com/osmlab/nycbuildings/issues/35

**Comment by planemad** [comment]
Thanks @lxbarth 

Capturing from Pg12 of http://www.nyc.gov/html/dcp/pdf/bytes/lion_metadata.pdf:
>**VALUE A**
Alternate Address Range: Alternative address ranges for the same street name. This can occur where buildings have been renumbered; old numbers will sometimes remain in use. For example, such usage is common in some Queens neighborhoods, including Far Rockaway, Douglaston, Forest Hills and Ridgewood, where non-hyphenated addresses have been replaced by hyphenated addresses.

>**VALUE B**
Alternative Street Names: Alternative street names that cannot be handled in the usual way.

**Comment by lxbarth** [comment]
We're all set here  - tbc on #139
