### ISSUE TITLE
Incorrect traffic direction on Montgomery Place, Brooklyn

### ISSUE THREAD

**Issue by bisoldi** [osmlab/nycbuildings#144]
Not entirely sure if your datasets control traffic directions, but thought I would post it here.  The traffic direction for Montgomery Place shows traffic headed towards the Park, while in reality traffic goes away from the Park and towards 8th Ave.

http://www.openstreetmap.org/way/5680039

![montgomeryplace](https://cloud.githubusercontent.com/assets/9962726/10136528/01d8e27e-65c3-11e5-85db-81b094269e10.jpg)

Attached is a screenshot from Google Maps, however I grew up on Montgomery Pl and can vouch for the inaccuracy.

![gmaps](https://cloud.githubusercontent.com/assets/9962726/10136647/818a93b4-65c3-11e5-8f64-b695c2274eb8.jpg)

**Comment by lxbarth** [comment]
Thanks for reporting. Indeed this dataset is not responsible for streets / oneways. Left a note on OSM http://www.openstreetmap.org/note/453829
