### ISSUE TITLE
Fix overlapping buildings

### ISSUE THREAD

**Issue by lxbarth** [osmlab/nycbuildings#31]
There are 150+ changesets uploaded before #8 generating overlapping building warnings.

Needs automated fix.

**Comment by Rub21** [comment]
@lxbarth @aaronlidman : 
I worked on this task and used [osmose data](http://osmose.openstreetmap.fr/export/) to identified all   points where buildings are in overlapping : https://github.com/osmlab/nycbuildings/tree/master/fixes/fix-overlapping , at total there are 4,198 points

[The map](https://api.tiles.mapbox.com/v4/ruben.d3aa9072/page.html?access_token=pk.eyJ1IjoicnViZW4iLCJhIjoiYlBrdkpRWSJ9.JgDDxJkvDn3us36aGzR6vg#12/40.6651/-73.9148) 

# Next action:
Someone  on team can work on fix the overlapping, and setup the map on background  on JOSM.
What do you think?

**Comment by aaronlidman** [comment]
@Rub21 Awesome. How common is this problem world-wide and in the United States? Can you get the # of those points?

Do you think this would be a good to-fix task?

**Comment by Rub21** [comment]
@aaronlidman :
The numbers are:
-  Entire world : 581,322 points
- United States : 45,269 points

> Do you think this would be a good to-fix task? 

This would be helpful on to-fix, such  as unconnected major and other items.

**Comment by aaronlidman** [comment]
@Rub21 Can you create a csv with all the issues in the United States? Does it include way ids? It would be useful to have that in the csv as well.

**Comment by Rub21** [comment]
@aaronlidman , that will be easy, but what is going to be the header(fields) on csv?, maybe do you have a sample?

**Comment by aaronlidman** [comment]
lat, lon, and elems will be great.

This will require some changes to to-fix, but if you get the data, I will show you where you need to make changes.

**Comment by Rub21** [comment]
@aaronlidman : 
This is the file: [us-overlapping-buildings.csv](https://gist.githubusercontent.com/Rub21/9b4502819d22e1e412a4/raw/us-overlapping-buildings.csv)

**Comment by lxbarth** [comment]
@Rub21 @aaronlidman - great. Those are a lot of points for US (45,269 points). Let's fix first NYC, then assess whether and how to tackle US?

**Comment by colinreilly** [comment]
I don’t see these overlaps in the source data. Out of curiosity what is causing this?

**Comment by emacsen** [comment]
The original data had higher resolution than OSM, so the buildings might occupy the same geometry without sharing node/ways, which the JOSM counts as an overlap.

Later (after a couple or few weeks), Alex an his team improved the processing by adding functionality that "snapped" these nodes/ways together, which eliminated the geometry errors.

**Comment by lxbarth** [comment]
@colinreilly - right, like @emacsen said, the overlaps we're talking about here are in the sub 1 foot area that were created by rounding errors.

**Comment by Rub21** [comment]
@aaronlidman 
>  Let's fix first NYC, then assess whether and how to tackle US?

files to : 
- [NYC](https://gist.githubusercontent.com/Rub21/047bbacdebaa81e54cd9/raw/nyc-buildings-overlapings.csv)
- [USA](https://gist.githubusercontent.com/Rub21/9b4502819d22e1e412a4/raw/us-overlapping-buildings.csv)

Let me know the those errors are on to-fix for fix

**Comment by lxbarth** [comment]
@Rub21 @aaronlidman - let's get those errors on to-fix and knock them out!

**Comment by aaronlidman** [comment]
- [New York City overlapping buildings task](http://osmlab.github.io/to-fix/#/task/nycbuildingoverlaps)
- [USA overlapping buildings task](http://localhost:3000/#/task/usabuildingoverlaps)

**Comment by Rub21** [comment]
@lxbarth @aaronlidman :

Cesar and Richman are going to start working on  [USA overlapping buildings task](http://osmlab.github.io/to-fix/#/task/usabuildingoverlaps)

**Comment by Rub21** [comment]
@aaronlidman :  I have [new file with overlapping buildings](https://dl.dropboxusercontent.com/u/43116811/osmose-files/nycbuildings.csv)(167 errors)  initially we had (4189 errors), Can you add. this one in to-fix.

**Comment by lxbarth** [comment]
@Rub21 @aaronlidman @ediyes - where are we here?

**Comment by Rub21** [comment]
@lxbarth @aaronlidman @ediyes : I found 33 overlap buildings, https://api.tiles.mapbox.com/v4/ruben.81ea8f44/page.html?access_token=pk.eyJ1IjoicnViZW4iLCJhIjoiYlBrdkpRWSJ9.JgDDxJkvDn3us36aGzR6vg#13/40.7389/-73.9381


@ediyes Podria trabajar esto el lunes .

`https://{switch:a,b,c}.tiles.mapbox.com/v4/ruben.81ea8f44/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnViZW4iLCJhIjoiYlBrdkpRWSJ9.JgDDxJkvDn3us36aGzR6vg`

**Comment by ediyes** [comment]
ok @Rub21 el lunes lo haré a primera hora.

**Comment by ediyes** [comment]
@Rub21  ya terminé con el trabajo, en dos lugares donde muestra la capa como error no encontré error alguno:
- https://www.openstreetmap.org/way/290696644/history
- https://www.openstreetmap.org/way/271892492/history

Puede revisarlo.

**Comment by lxbarth** [comment]
Done here.
