### ISSUE TITLE
Duplicate "magic" BINs

### ISSUE THREAD

**Issue by pnorman** [osmlab/nycbuildings#69]
My recollection was that `nycdoitt:bin` was kept around because it was a unique identifier that would make it easier in the future to integrate updates from NYC. I admit that I can't find this in the import documentation, but it might of been in a google+ meeting.

Ways [247624968](http://www.openstreetmap.org/way/247624968) and [247624969](http://www.openstreetmap.org/way/247624969) have duplicate magic values of `nycdoitt:bin=3000000`. These magic values should be documented on the import's page on the wiki, and we should consider if these special values should be kept.

**Comment by 0xStarcat** [comment]
just wow
